import React, { useMemo } from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

interface FluentMarkdownProps {
  content: string;
  className?: string;
}

/**
 * Normalizes LaTeX math syntax generated by LLMs to ensure reliable rendering in KaTeX:
 * 1. Replaces display math \[ ... \] with $$ ... $$
 * 2. Replaces inline math \( ... \) with $ ... $
 * 3. In piecewise/matrix blocks (\begin{cases}, \begin{aligned}, etc.), ensures single backslash line-breaks
 *    like "\ -5" or "\ \text" are upgraded to double backslashes "\\ " for proper row breaking.
 * 4. Ensures un-delimited \begin{cases}...\end{cases} blocks are wrapped in $$...$$
 */
export function normalizeLatexMath(raw: string): string {
  if (!raw) return '';

  let text = raw;

  // 1. Convert \[ ... \] to $$ ... $$
  text = text.replace(/\\\[([\s\S]*?)\\\]/g, (_, math) => `\n\n$$\n${math.trim()}\n$$\n\n`);

  // 2. Convert \( ... \) to $ ... $
  text = text.replace(/\\\(([\s\S]*?)\\\)/g, (_, math) => `$${math.trim()}$`);

  // 3. Wrap bare LaTeX environments (\begin{cases|matrix|pmatrix|bmatrix|aligned|array}) not already enclosed in $$
  text = text.replace(
    /(?<!\$)\s*(\\begin\{(?:cases|matrix|pmatrix|bmatrix|aligned|array|gather|equation)\}[\s\S]*?\\end\{(?:cases|matrix|pmatrix|bmatrix|aligned|array|gather|equation)\})\s*(?!\$)/g,
    (_, env) => `\n\n$$\n${env.trim()}\n$$\n\n`
  );

  // 4. Fix row separators inside environments where LLMs emit single backslash instead of double backslash (e.g. \ -5 & \text)
  text = text.replace(
    /(\$\$[\s\S]*?\$\$)|(\\begin\{(?:cases|matrix|pmatrix|bmatrix|aligned|array)\}[\s\S]*?\\end\{(?:cases|matrix|pmatrix|bmatrix|aligned|array)\})/g,
    (match) => {
      // In this math block, convert single backslash followed by whitespace and a new entry to \\
      // E.g.: `\ -5` or `\ +10` or `\ \text` or `\ 0` -> `\\ -5` or `\\ +10`
      return match.replace(/(?<!\\)\\\s+([+\-\d]|\\text)/g, '\\\\ $1');
    }
  );

  // 5. Ensure block math $$ is cleanly isolated with newlines for robust remark-math AST parsing
  text = text.replace(/\$\$([\s\S]*?)\$\$/g, (_, inner) => {
    return `\n\n$$\n${inner.trim()}\n$$\n\n`;
  });

  return text;
}

export const FluentMarkdown: React.FC<FluentMarkdownProps> = ({ content, className = '' }) => {
  const processedContent = useMemo(() => normalizeLatexMath(content), [content]);

  return (
    <div className={`fluent-markdown ${className}`}>
      <Markdown
        remarkPlugins={[remarkGfm, [remarkMath, { singleDollarTextMath: true }]]}
        rehypePlugins={[
          [
            rehypeKatex,
            {
              throwOnError: false,
              strict: false,
              output: 'htmlAndMathml',
              errorColor: '#f43f5e',
            },
          ],
        ]}
        components={{
          a: ({ node, ...props }) => (
            <a {...props} target="_blank" rel="noopener noreferrer" className="hover:underline" />
          ),
        }}
      >
        {processedContent}
      </Markdown>
    </div>
  );
};

export default FluentMarkdown;
